### PR TITLE
Add "msvs" toolset for creating projects usable with any MSVS 201x version

### PR DESCRIPTION
**Pull request by vadz**
I think this should eventually replace `vs201x` toolsets, but for now I've just added this one in parallel with them.

Please let me know if you have any comments about this approach or any details of its realization.

See #118.

### CODE REVIEW

**Comment by vslavik** [comment]
Sorry for the delay. This is more complicated than I expected, but looks good to me — and I agree should be done. Thanks a lot!

It is worth saying explicitly that this is a shift from "generate as MSVS would created the project" to "generate something that works", but I think that's the right approach for MSBuild-based projects.

If I understand it correctly, it is still necessary to have per-version sln files? Is there no way to have a single solution file too? (I would expect `MinimumVisualStudioVersion` to exist in sln files to facilitate cross-version compatibility.)

**Comment by vadz** [comment]
> Sorry for the delay. 

No problem and thanks a lot for looking at it!

> This is more complicated than I expected,

This is actually a simpler version than what I started doing initially, by trying to combine the existing toolsets together. I admit don't really see how could it be done in any simpler way, please let me know if you have any ideas.

> It is worth saying explicitly that this is a shift from "generate as MSVS would created the project" to "generate something that works", but I think that's the right approach for MSBuild-based projects.

Yes, I agree with this now (only 10 years later...).

> If I understand it correctly, it is still necessary to have per-version sln files? Is there no way to have a single solution file too? (I would expect `MinimumVisualStudioVersion` to exist in sln files to facilitate cross-version compatibility.)

I don't know how to have a version-neutral solution file. AFAICS it must have `VisualStudioVersion` in it, and what can we put it in it? Having different solution files also opens them in the right MSVS version if you have more than one of them installed. I'm not very satisfied with having
```
msvs2013.solutionfile = build/foo_msvc12.sln;
msvs2015.solutionfile = build/foo_msvc14.sln;
msvs2017.solutionfile = build/foo_msvc141.sln;
msvs2019.solutionfile = build/foo_msvc142.sln;
```
but neither do I see how could anything like this be achieved otherwise. There is no standard convention for naming these files (in addition the above any of `2013, 2015, 2017, 2019`, `12, 14, 15, 16`, `120, 140, 141, 142` with any combination of no prefix, `vs`, `msvs`, `vc` or `msvc` potentially make as much or even more sense), so I just gave up. Again, please let me know if you have any suggestions.

BTW, I'd like to make a new release after merging this. I know not many people use bkl, but some still do, and it's nice to show them that the project is still alive, in spite of the ambient CMakization of everything.

**Comment by vslavik** [comment]
> I admit don't really see how could it be done in any simpler way

Me neither, I meant that it is (inherently) trickier than I expected.

> I don't know how to have a version-neutral solution file. AFAICS it must have VisualStudioVersion in it, and what can we put it in it? Having different solution files also opens them in the right MSVS version if you have more than one of them installed. 
…
> Again, please let me know if you have any suggestions.

I'd rather have (by default, or even non-default, but doable) single solution file. I think it is possible and is the reason why sln files contain both `VisualStudioVersion ` and `MinimumVisualStudioVersion` - and that it's the VS version chooser helper, and the (presumably) atypical situation of having multiple VS versions installed, that is causing trouble.

I tried to test that theory by doing the following: I still had VS2017 installed, so I uninstalled VS2019 and kept '17. I then tried opening a solution file made with and for VS2019. At first this resulted in the VS version picker (with an empty list to choose from). When I manually did Open with and picked VS2017, it opened the solution without problems, except for warning about the compiler toolset version being unavailable (something addressed in this PR). After that, and closing VS2017, clicking the same solution file in Explorer directly opened it in VS2017.

**Comment by vadz** [comment]
Sorry for the delay, I've finally implemented generating solution files by default by just generating a MSVS 2019 solution file in this case. Please let me know if this corresponds the behaviour you had in mind, AFAICS it should be.

**Comment by vadz** [comment]
I'd like to finally merge this, do you have any objections?

**Comment by vslavik** [comment]
> do you have any objections?

Not at all; sorry, I thought that was clear from the above. Thanks!

**Comment by vadz** [comment]
Um, nothing like preparing to merge a PR to find another potential problem with it :-( I've thought about another project to test this with and I see that `msvs` toolset works slightly differently from `vs201x` one there, I'm not totally sure if it's really a problem but will have to look at this to be totally sure, so please don't be surprised if I don't merge this immediately.

**Comment by vslavik** [comment]
> Um, nothing like preparing to merge a PR to find another potential problem with it :-( 

I think I found another — I used this much-needed nudge to finally unify WinSparkle's project files and it's failing. I (think I) understand why at the high level: information about sub-solutions is being lost when `generate-solution=false` (previously, or not with `msvs` toolset, solution objects were created, but not written out, while now they're not created). But I'm a bit lost about how the changes triggered this and how to fix it — would you have any idea?

To reproduce:
```
$ git clone -b unified-msvs-solution https://github.com/vslavik/winsparkle.git 
$ cd winsparkle
$ bkl -v WinSparkle.bkl
processing WinSparkle.bkl
processing 3rdparty/dependencies.bkl
processing 3rdparty/expat.bkl
processing 3rdparty/libcrypto.bkl
processing 3rdparty/wxWidgets.bkl
processing examples/examples.bkl
U	WinSparkle.vcxproj
U	WinSparkle.vcxproj.filters
U	3rdparty/expat.vcxproj
.	3rdparty/expat.vcxproj.filters
U	3rdparty/libcrypto.vcxproj
U	3rdparty/libcrypto.vcxproj.filters
U	3rdparty/wx.vcxproj
U	3rdparty/wx.vcxproj.filters
U	examples/example_psdk.vcxproj
U	examples/example_psdk.vcxproj.filters
Traceback (most recent call last):
  File "/Users/vaclav/Development/bkl-ng/bkl", line 160, in <module>
    intr.process_file(args[0])
  File "/Users/vaclav/Development/bkl-ng/src/bkl/interpreter/__init__.py", line 112, in process_file
    self.process(parse_file(filename))
  File "/Users/vaclav/Development/bkl-ng/src/bkl/interpreter/__init__.py", line 107, in process
    self.generate()
  File "/Users/vaclav/Development/bkl-ng/src/bkl/interpreter/__init__.py", line 246, in generate
    self.generate_for_toolset(toolsets[-1], skip_making_copy=True)
  File "/Users/vaclav/Development/bkl-ng/src/bkl/interpreter/__init__.py", line 258, in generate_for_toolset
    bkl.api.Toolset.get(toolset).generate(model)
  File "/Users/vaclav/Development/bkl-ng/src/bkl/plugins/vsbase.py", line 809, in generate
    m.solution.write()
  File "/Users/vaclav/Development/bkl-ng/src/bkl/plugins/vs201x.py", line 900, in write
    s.write()
  File "/Users/vaclav/Development/bkl-ng/src/bkl/plugins/vsbase.py", line 634, in write
    outf.write("\t\t{%(g)s} = {%(g)s}\n" % {'g':self._get_target_guid(d)})
  File "/Users/vaclav/Development/bkl-ng/src/bkl/plugins/vsbase.py", line 592, in _get_target_guid
    assert guid, "can't find GUID of project '%s'" % id
AssertionError: can't find GUID of project 'WinSparkle_expat'
$
```
After commenting out the `msvs.generate-solution = false;` line in all 3rdparty/*.bkl files, the build succeeds (but creates some extra files). Something weird is going out with `msvs.option.IntDir` output (from 3rdparty/dependencies.bkl) then too, but I didn't investigate further yet — the generated vcxproj files are manually adjusted a little bit anyway.

**Comment by vadz** [comment]
Oops. I'll check this a.s.a.p...

**Comment by vadz** [comment]
Hmm, weirdly enough, I get a _different_ error, before I can even get to the one you see:
```
Traceback (most recent call last):
  File "c:/src/bakefile/github/src/tool.py", line 160, in <module>
    intr.process_file(args[0])
  File "/cygdrive/c/src/bakefile/github/src/bkl/interpreter/__init__.py", line 112, in process_file
    self.process(parse_file(filename))
  File "/cygdrive/c/src/bakefile/github/src/bkl/interpreter/__init__.py", line 107, in process
    self.generate()
  File "/cygdrive/c/src/bakefile/github/src/bkl/interpreter/__init__.py", line 246, in generate
    self.generate_for_toolset(toolsets[-1], skip_making_copy=True)
  File "/cygdrive/c/src/bakefile/github/src/bkl/interpreter/__init__.py", line 258, in generate_for_toolset
    bkl.api.Toolset.get(toolset).generate(model)
  File "/cygdrive/c/src/bakefile/github/src/bkl/plugins/vsbase.py", line 802, in generate
    self.gen_for_module(m)
  File "/cygdrive/c/src/bakefile/github/src/bkl/plugins/vsbase.py", line 844, in gen_for_module
    self.gen_for_target(t, prj)
  File "/cygdrive/c/src/bakefile/github/src/bkl/plugins/vs201x.py", line 414, in gen_for_target
    f.commit()
  File "/cygdrive/c/src/bakefile/github/src/bkl/io.py", line 163, in commit
    os.makedirs(dirname)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: './3rdparty/expat/expat/lib/../../..'
```

And if I rerun it again, I get the same thing but with
```
OSError: [Errno 17] File exists: './3rdparty/openssl/crypto/../..'
```

But if I then run it _again_, then I finally get the error you see (and which I'll try to debug now).

Should I have used `--recurse-submodules` in my clone command? Or is there some problem with Cygwin Python (but I've always used it with bkl without any problems so far)?

**Comment by vadz** [comment]
I've probably broken this with 8e4c7dc75305897a24ea4bd76725844ef7db2ee1 and not any of "msvs" changes themselves... The idea of using `VSSolutionNull` seemed more elegant and simpler, but its `add_subsolution()` does nothing. breaking the GUIDs search and probably external dependencies too. I'll make a PR fixing this a.s.a.p.

**Comment by vslavik** [comment]
> The idea of using VSSolutionNull seemed more elegant and simpler, but its add_subsolution() does nothing. breaking the GUIDs search and probably external dependencies too. 

That was my assumption, and I tried to implement it "properly", but couldn't really figure it out.

> I'll make a PR fixing this a.s.a.p.

Thanks! Don't worry about the asap part though, it really isn't anything to hurry about.

**Comment by vslavik** [comment]
> Should I have used --recurse-submodules in my clone command?

Yes (sorry!). I didn't realize this would affect and even replied to that effect at first, but it may if the srcdir isn't there I think.

**Pull request merged**
